// Code generated by go-swagger; DO NOT EDIT.

package top

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"ranking/models"
)

// AddPlayerOKCode is the HTTP code returned for type AddPlayerOK
const AddPlayerOKCode int = 200

/*AddPlayerOK List add score  players

swagger:response addPlayerOK
*/
type AddPlayerOK struct {

	/*
	  In: Body
	*/
	Payload *models.Player `json:"body,omitempty"`
}

// NewAddPlayerOK creates AddPlayerOK with default headers values
func NewAddPlayerOK() *AddPlayerOK {

	return &AddPlayerOK{}
}

// WithPayload adds the payload to the add player o k response
func (o *AddPlayerOK) WithPayload(payload *models.Player) *AddPlayerOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add player o k response
func (o *AddPlayerOK) SetPayload(payload *models.Player) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddPlayerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddPlayerBadRequestCode is the HTTP code returned for type AddPlayerBadRequest
const AddPlayerBadRequestCode int = 400

/*AddPlayerBadRequest Bad Request

swagger:response addPlayerBadRequest
*/
type AddPlayerBadRequest struct {
}

// NewAddPlayerBadRequest creates AddPlayerBadRequest with default headers values
func NewAddPlayerBadRequest() *AddPlayerBadRequest {

	return &AddPlayerBadRequest{}
}

// WriteResponse to the client
func (o *AddPlayerBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// AddPlayerNotFoundCode is the HTTP code returned for type AddPlayerNotFound
const AddPlayerNotFoundCode int = 404

/*AddPlayerNotFound Players Not Found

swagger:response addPlayerNotFound
*/
type AddPlayerNotFound struct {
}

// NewAddPlayerNotFound creates AddPlayerNotFound with default headers values
func NewAddPlayerNotFound() *AddPlayerNotFound {

	return &AddPlayerNotFound{}
}

// WriteResponse to the client
func (o *AddPlayerNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// AddPlayerInternalServerErrorCode is the HTTP code returned for type AddPlayerInternalServerError
const AddPlayerInternalServerErrorCode int = 500

/*AddPlayerInternalServerError Server Error

swagger:response addPlayerInternalServerError
*/
type AddPlayerInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewAddPlayerInternalServerError creates AddPlayerInternalServerError with default headers values
func NewAddPlayerInternalServerError() *AddPlayerInternalServerError {

	return &AddPlayerInternalServerError{}
}

// WithPayload adds the payload to the add player internal server error response
func (o *AddPlayerInternalServerError) WithPayload(payload string) *AddPlayerInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add player internal server error response
func (o *AddPlayerInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddPlayerInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
