// Code generated by go-swagger; DO NOT EDIT.

package top

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewAddPlayerParams creates a new AddPlayerParams object
//
// There are no default values defined in the spec.
func NewAddPlayerParams() AddPlayerParams {

	return AddPlayerParams{}
}

// AddPlayerParams contains all the bound params for the add player operation
// typically these are obtained from a http.Request
//
// swagger:parameters addPlayer
type AddPlayerParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	IsRelative bool
	/*
	  Required: true
	  In: path
	*/
	PlayerID int64
	/*
	  Required: true
	  In: path
	*/
	Points string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewAddPlayerParams() beforehand.
func (o *AddPlayerParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rIsRelative, rhkIsRelative, _ := route.Params.GetOK("isRelative")
	if err := o.bindIsRelative(rIsRelative, rhkIsRelative, route.Formats); err != nil {
		res = append(res, err)
	}

	rPlayerID, rhkPlayerID, _ := route.Params.GetOK("playerId")
	if err := o.bindPlayerID(rPlayerID, rhkPlayerID, route.Formats); err != nil {
		res = append(res, err)
	}

	rPoints, rhkPoints, _ := route.Params.GetOK("points")
	if err := o.bindPoints(rPoints, rhkPoints, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindIsRelative binds and validates parameter IsRelative from path.
func (o *AddPlayerParams) bindIsRelative(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("isRelative", "path", "bool", raw)
	}
	o.IsRelative = value

	return nil
}

// bindPlayerID binds and validates parameter PlayerID from path.
func (o *AddPlayerParams) bindPlayerID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("playerId", "path", "int64", raw)
	}
	o.PlayerID = value

	return nil
}

// bindPoints binds and validates parameter Points from path.
func (o *AddPlayerParams) bindPoints(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Points = raw

	return nil
}
