// Code generated by go-swagger; DO NOT EDIT.

package top

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"ranking/models"
)

// TopListOKCode is the HTTP code returned for type TopListOK
const TopListOKCode int = 200

/*TopListOK List the top players

swagger:response topListOK
*/
type TopListOK struct {

	/*
	  In: Body
	*/
	Payload models.PlayersList `json:"body,omitempty"`
}

// NewTopListOK creates TopListOK with default headers values
func NewTopListOK() *TopListOK {

	return &TopListOK{}
}

// WithPayload adds the payload to the top list o k response
func (o *TopListOK) WithPayload(payload models.PlayersList) *TopListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the top list o k response
func (o *TopListOK) SetPayload(payload models.PlayersList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TopListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.PlayersList{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// TopListBadRequestCode is the HTTP code returned for type TopListBadRequest
const TopListBadRequestCode int = 400

/*TopListBadRequest Bad Request

swagger:response topListBadRequest
*/
type TopListBadRequest struct {
}

// NewTopListBadRequest creates TopListBadRequest with default headers values
func NewTopListBadRequest() *TopListBadRequest {

	return &TopListBadRequest{}
}

// WriteResponse to the client
func (o *TopListBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// TopListNotFoundCode is the HTTP code returned for type TopListNotFound
const TopListNotFoundCode int = 404

/*TopListNotFound Players Not Found

swagger:response topListNotFound
*/
type TopListNotFound struct {
}

// NewTopListNotFound creates TopListNotFound with default headers values
func NewTopListNotFound() *TopListNotFound {

	return &TopListNotFound{}
}

// WriteResponse to the client
func (o *TopListNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// TopListInternalServerErrorCode is the HTTP code returned for type TopListInternalServerError
const TopListInternalServerErrorCode int = 500

/*TopListInternalServerError Server Error

swagger:response topListInternalServerError
*/
type TopListInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewTopListInternalServerError creates TopListInternalServerError with default headers values
func NewTopListInternalServerError() *TopListInternalServerError {

	return &TopListInternalServerError{}
}

// WithPayload adds the payload to the top list internal server error response
func (o *TopListInternalServerError) WithPayload(payload string) *TopListInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the top list internal server error response
func (o *TopListInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TopListInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
