// Code generated by go-swagger; DO NOT EDIT.

package top

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// TopListRelativeURL generates an URL for the top list relative operation
type TopListRelativeURL struct {
	Players  int64
	Position int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *TopListRelativeURL) WithBasePath(bp string) *TopListRelativeURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *TopListRelativeURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *TopListRelativeURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/top/position/{position}/players/{players}"

	players := swag.FormatInt64(o.Players)
	if players != "" {
		_path = strings.Replace(_path, "{players}", players, -1)
	} else {
		return nil, errors.New("players is required on TopListRelativeURL")
	}

	position := swag.FormatInt64(o.Position)
	if position != "" {
		_path = strings.Replace(_path, "{position}", position, -1)
	} else {
		return nil, errors.New("position is required on TopListRelativeURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *TopListRelativeURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *TopListRelativeURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *TopListRelativeURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on TopListRelativeURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on TopListRelativeURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *TopListRelativeURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
