// Code generated by go-swagger; DO NOT EDIT.

package top

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewTopListRelativeParams creates a new TopListRelativeParams object
//
// There are no default values defined in the spec.
func NewTopListRelativeParams() TopListRelativeParams {

	return TopListRelativeParams{}
}

// TopListRelativeParams contains all the bound params for the top list relative operation
// typically these are obtained from a http.Request
//
// swagger:parameters topListRelative
type TopListRelativeParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	Players int64
	/*
	  Required: true
	  In: path
	*/
	Position int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewTopListRelativeParams() beforehand.
func (o *TopListRelativeParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rPlayers, rhkPlayers, _ := route.Params.GetOK("players")
	if err := o.bindPlayers(rPlayers, rhkPlayers, route.Formats); err != nil {
		res = append(res, err)
	}

	rPosition, rhkPosition, _ := route.Params.GetOK("position")
	if err := o.bindPosition(rPosition, rhkPosition, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindPlayers binds and validates parameter Players from path.
func (o *TopListRelativeParams) bindPlayers(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("players", "path", "int64", raw)
	}
	o.Players = value

	return nil
}

// bindPosition binds and validates parameter Position from path.
func (o *TopListRelativeParams) bindPosition(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("position", "path", "int64", raw)
	}
	o.Position = value

	return nil
}
